#ifndef AS5045COMMUNICATIONLIB_GLOBAL_H
#define AS5045COMMUNICATIONLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AS5045COMMUNICATIONLIB_LIBRARY)
#  define AS5045COMMUNICATIONLIB_EXPORT Q_DECL_EXPORT
#else
#  define AS5045COMMUNICATIONLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // AS5045COMMUNICATIONLIB_GLOBAL_H
